<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class TermiiService
{
    protected string $apiKey;
    protected string $senderId;
    protected string $baseUrl;

    public function __construct()
    {
        $this->apiKey = config('services.termii.api_key');
        $this->senderId = config('services.termii.sender_id');
        $this->baseUrl = config('services.termii.base_url');
    }

    /**
     * Send a standard SMS message.
     * Channels: 'generic' (promotional), 'dnd' (transactional/bypasses DND), 'whatsapp'
     */
    public function sendSms(string $to, string $message, string $channel = 'generic'): array
    {
        $response = Http::post("{$this->baseUrl}/api/sms/send", [
            'api_key' => $this->apiKey,
            'to' => $to,
            'from' => $this->senderId,
            'sms' => $message,
            'type' => 'plain',
            'channel' => $channel,
        ]);

        if ($response->failed()) {
            Log::error('Termii SMS Error', ['response' => $response->json()]);
        }

        return $response->json();
    }

    /**
     * Send an OTP Code using Termii's Token API.
     */
    public function sendOtp(string $to, string $pinPlaceholder = '< 1234 >'): array
    {
        $response = Http::post("{$this->baseUrl}/api/sms/otp/send", [
            'api_key' => $this->apiKey,
            'message_type' => 'NUMERIC',
            'to' => $to,
            'from' => $this->senderId,
            'channel' => 'dnd',
            'pin_attempts' => 3,
            'pin_time_to_live' => 10,
            'pin_length' => 6,
            'pin_placeholder' => $pinPlaceholder,
            'message_text' => "Your verification code is {$pinPlaceholder}",
            'pin_type' => 'NUMERIC',
        ]);

        return $response->json();
    }

    /**
     * Verify an OTP Code generated by Termii.
     */
    public function verifyOtp(string $pinId, string $pin): array
    {
        $response = Http::post("{$this->baseUrl}/api/sms/otp/verify", [
            'api_key' => $this->apiKey,
            'pin_id' => $pinId,
            'pin' => $pin,
        ]);

        return $response->json();
    }
}
